[[pages]]
path = "pages/1_disaster_prevention_museum_booking.py"
name = "é˜²ç½é¤¨åƒé¤¨é ç´„"
icon = "ğŸ“¢"

[[pages]]
path = "pages/2_community_meal_delivery.py"
name = "ç¤¾å€äº’åŠ©é€é¤"
icon = "ğŸ±"

[[pages]]
path = "pages/3_public_application_and_inquiry.py"
name = "æ°‘çœ¾ç”³è¾¦èˆ‡æŸ¥è©¢"
icon = "ğŸ“"

[[pages]]
path = "pages/4_case_review.py"
name = "æ¡ˆä»¶å¯©æ ¸"
icon = "ğŸ‘®"

[[pages]]
path = "pages/5_auto_comparison_system.py"
name = "ç”³å ±æ›¸æ¯”å°ç³»çµ±"
icon = "ğŸš’"
